# -*- coding: utf-8 -*-
"""trabalho pratico mod1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IBGE9ZOqm_W_IGWOYQ7Md6Nu3uLHpQzK

#Qual é o valor presente de um título pré-fixado com taxa de 14,5% com pagamentos de cupom com intervalos de 120, 248, 372 e 499 dias úteis em relação à data de hoje? No caso em que o investidor venda o título depois de 248 dias úteis, recebendo dois cupons, um depois de 120 dias úteis e outro depois de 248 dias úteis, que é quando ele vende o título, qual é a rentabilidade bruta do período, supondo que ele reinvestiu o valor do primeiro cupom à mesma taxa em que comprou o título?
"""

import numpy as np

def vp(taxa, list_du):
    vf = 1_000 # reais
    tx_c = 10 # % a.a.
    list_num = len(list_du)*[vf*((1 + tx_c/100)**(1/2) - 1)]
    list_num[-1] += vf
    list_vp = []
    for du, num in zip(list_du, list_num):
        temp_vp = num/(1 + taxa/100)**(du/252)
        list_vp.append(temp_vp)
    vp = np.sum(list_vp)
    return vp

def venda_antecipada(list_du, pv_compra, tx_venda, du_venda, tipo='r'):
        vf = 1_000
        tx_c = 10
        list_num = len(list_du)*[vf*((1 + tx_c/100)**(1/2) - 1)]
        list_num[-1] += vf
        list_pv = []
        list_cup = []
        for du, num in zip(list_du, list_num):
            if du_venda < du:
                temp_pv = num/(1 + tx_venda/100)**((du - du_venda)/252)
                list_pv.append(temp_pv)
            else:
                list_cup.append(num*(1 + tx_venda/100)**((du_venda - du)/252) if tipo == 'r' else num)
        pv_venda = np.sum(list_pv)
        valor_bruto_resgate = np.sum(list_cup) + pv_venda
        rb = valor_bruto_resgate/pv_compra - 1
        rba = (1 + rb)**(252/du_venda) - 1 
        
        return pv_venda, rb*100, rba*100

tx = 14.5 #%
list_du = [120, 248, 372, 499]
v_p = vp(tx, list_du)
print(f'O valor presente deste titulo eh R${np.round(v_p,2)}')

list_du = [120, 248, 372, 499]
du_venda = 248
tx_venda = 12.98
vendaant, rbt, rbta = venda_antecipada(list_du, v_p, tx_venda, du_venda, tipo = 'r')
print(f'O valor de venda do titulo foi R${np.round(vendaant,2)}, o rendimento bruto {np.round(rbt,2)}% a.p, sendo {np.round(rbta,2)}% a.a')